const LIST_OF_APPS = [
  {
    title: "AI Prompts",
    description:
      "Unlock your creativity with AI Prompts, generating endless inspiration for your next project or idea.",
    link: "/apps/ai-prompts",
    icon: "🤖",
    tag: "General",
    isComplete: true,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "Audio Downloader",
    description:
      "Effortlessly download audio with the Audio Downloader, for offline enjoyment of your favorite music and podcasts.",
    link: "/apps/audio-downloader",
    icon: "🎵",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Media"],
  },
  {
    title: "Calculator",
    description:
      "Perform quick and accurate mathematical calculations for various needs.",
    link: "/apps/calculator",
    icon: "🧮",
    tag: "General",
    isComplete: true,
    categories: ["Utility", "General"],
  },
  {
    title: "Color Generator",
    description: "Generate beautiful colors for your design projects.",
    link: "/apps/color-generator",
    icon: "🎨",
    tag: "General",
    isComplete: true,
    categories: ["Utility"],
  },
  {
    title: "Cookie Details",
    description:
      "Gain insight into website cookies with Cookie Details, offering transparency and browsing control.",
    link: "/apps/cookie-details",
    icon: "🍪",
    tag: "Latest",
    isComplete: true,
    categories: ["Security", "Utility"],
  },
  {
    title: "Countdown",
    description: "Set up countdowns for important events or deadlines.",
    link: "/apps/countdown",
    icon: "⏳",
    tag: "General",
    isComplete: true,
    categories: ["Productivity"],
  },
  {
    title: "Currency Converter",
    description:
      "Enable seamless currency conversion with the Currency Converter, offering up-to-date exchange rates.",
    link: "/apps/currency-converter",
    icon: "💲",
    tag: "Latest",
    isComplete: true,
    categories: ["Finance", "Utility"],
  },
  {
    title: "Document Converter",
    description:
      "Convert document files into other formats (pdf, doc, odt, etc).",
    link: "/apps/document-converter",
    icon: "📝",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "Video Converter",
    description:
      "Convert Video files to other formats like MP4, MOV, AVI, etc.",
    link: "/apps/video-converter",
    icon: "🎥",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Media"],
  },
  {
    title: "Audio Converter",
    description:
      "Convert audio files to other audio formats like MP3, WAV, etc.",
    link: "/apps/audio-converter",
    icon: "🎵",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Media"],
  },
  {
    title: "Horoscope",
    description: "Get insights into your future with daily horoscope readings.",
    link: "/apps/horoscope",
    icon: "🔮",
    tag: "General",
    isComplete: false,
    categories: ["General"],
  },
  {
    title: "Image Editor",
    description:
      "Refine visuals effortlessly using the Image Editor, ideal for enhancing photos and graphics.",
    link: "/apps/image-editor",
    icon: "🖼️",
    tag: "Latest",
    isComplete: false,
    categories: ["Media"],
  },
  {
    title: "Interest Calculator",
    description: "Calculate interest for loans, savings, and investments.",
    link: "/apps/interest-calculator",
    icon: "💰",
    tag: "General",
    isComplete: true,
    categories: ["Finance", "Utility"],
  },
  {
    title: "Jokes",
    description:
      "Experience daily doses of laughter with a delightful array of humor, providing the perfect mood boost for every occasion.",
    link: "/apps/jokes",
    icon: "🎭",
    tag: "General",
    isComplete: true,
    categories: ["Entertainment"],
  },
  {
    title: "Name Generator",
    description: "Generate random names for characters, products, and more.",
    link: "/apps/name-generator",
    icon: "📛",
    tag: "General",
    isComplete: false,
    categories: ["Utility"],
  },
  {
    title: "Password Generator",
    description: "Create secure passwords with the Password Generator tool.",
    link: "/apps/password-generator",
    icon: "🔐",
    tag: "General",
    isComplete: true,
    categories: ["Security", "Utility"],
  },
  {
    title: "Image Compressor",
    description:
      "Compress image files (JPG, PNG, WEBP, AVIF, etc.) to smaller size.",
    link: "/apps/image-compressor",
    icon: "🖼️",
    tag: "Latest",
    isComplete: true,
    categories: ["Utility", "Media"],
  },
  {
    title: "Image Converter",
    description:
      "Convert image files to other image formats such as JPG, PNG, WEBP, AVIF etc.",
    link: "/apps/image-converter",
    icon: "🖼️",
    tag: "General",
    isComplete: true,
    categories: ["Utility", "Media"],
  },
  {
    title: "QR Generator",
    description:
      "Generate QR codes instantly with the QR Generator, simplifying data sharing and communication.",
    link: "/apps/qr-generator",
    icon: "🏁",
    tag: "Latest",
    isComplete: true,
    categories: ["Utility"],
  },
  {
    title: "Quotes",
    icon: "💭",
    description:
      "Discover inspiration through an incredible selection of thought-provoking quotes to inspire, and motivate you.",
    link: "/apps/quotes",
    tag: "Latest",
    isComplete: true,
    categories: ["General"],
  },
  {
    title: "Sitemap Compiler",
    description:
      "Simplify website organization with the Sitemap Compiler, making `sitemap.xml` generation effortless.",
    link: "/apps/sitemap-compiler",
    icon: "🗊",
    tag: "Latest",
    isComplete: true,
    categories: ["Utility"],
  },
  {
    title: "Sort Lists",
    description:
      "Quickly sort lists with the Sort Lists tool, facilitating better organization and management.",
    link: "/apps/sort-lists",
    icon: "🔀",
    tag: "General",
    isComplete: true,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "Summary Generator",
    description:
      "Save time by reading summaries generated by the Summary Generator instead of reading lengthy articles.",
    link: "/apps/summary-generator",
    icon: "🗒",
    tag: "Latest",
    isComplete: false,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "Tic-Tac-Toe",
    description:
      "Enjoy classic fun and challenge your friends with the Tic-Tac-Toe game, perfect for passing the time.",
    link: "/apps/tic-tac-toe",
    icon: "❌",
    tag: "General",
    isComplete: true,
    categories: ["Entertainment"],
  },
  {
    title: "Timer",
    description:
      "Enhance productivity and time management with timer, ensuring focused task completion.",
    link: "/apps/timer",
    icon: "⏱️",
    tag: "General",
    isComplete: true,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "To-Do",
    description:
      "Stay organized and on top of your tasks with the To-Do App for management of your daily agenda and deadlines.",
    link: "/apps/to-do",
    icon: "🎯",
    tag: "Latest",
    isComplete: true,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "Translator",
    description:
      "Translate your text into over 100 plus languages using the translator tool.",
    link: "/apps/translator",
    icon: "🔣",
    tag: "General",
    isComplete: true,
    categories: ["Utility"],
  },
  {
    title: "Video Downloader",
    description:
      "Effortlessly download videos with the Video Downloader, enabling offline viewing of your favorite content.",
    link: "/apps/video-downloader",
    icon: "▶️",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Media"],
  },
  {
    title: "Video Editor",
    description:
      "Elevate your videos with the Video Editor, offering powerful editing tools for professional-quality content.",
    link: "/apps/video-editor",
    icon: "🎞️",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Media"],
  },
  {
    title: "World Clock",
    description:
      "Keep track of time around the globe with the World Clock, providing real-time updates for various time zones.",
    link: "/apps/world-clock",
    icon: "🕓",
    tag: "Latest",
    isComplete: true,
    categories: ["Productivity", "Utility"],
  },
];

export default LIST_OF_APPS;
