const LIST_OF_APPS = [
  {
    title: "AI Prompts",
    description:
      "Unlock your creativity with AI Prompts, generating endless inspiration for your next project or idea.",
    link: "/apps/ai-prompts",
    icon: "🤖",
    tag: "General",
    isComplete: true,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "Audio Downloader",
    description:
      "Effortlessly download audio with the Audio Downloader, for offline enjoyment of your favorite music and podcasts.",
    link: "/apps/audio-downloader",
    icon: "🎵",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Media"],
  },
  {
    title: "Book Summary",
    description: "Read summarize books to get key insights and save time.",
    link: "/apps/book-summary",
    icon: "📚",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "General"],
  },
  {
    title: "Calculator",
    description:
      "Perform quick and accurate mathematical calculations for various needs.",
    link: "/apps/calculator",
    icon: "🧮",
    tag: "General",
    isComplete: false,
    categories: ["Utility", "General"],
  },
  {
    title: "Color Generator",
    description: "Generate beautiful colors for your design projects.",
    link: "/apps/color-generator",
    icon: "🎨",
    tag: "General",
    isComplete: true,
    categories: ["General"],
  },
  {
    title: "Cookie Details",
    description:
      "Gain insight into website cookies with Cookie Details, offering transparency and browsing control.",
    link: "/apps/cookie-details",
    icon: "🍪",
    tag: "Latest",
    isComplete: false,
    categories: ["Security", "Utility"],
  },
  {
    title: "Countdown",
    description: "Set up countdowns for important events or deadlines.",
    link: "/apps/countdown",
    icon: "⏳",
    tag: "General",
    isComplete: true,
    categories: ["Productivity"],
  },
  {
    title: "Crossword",
    description:
      "Challenge yourself with the interactive Crossword puzzle, perfect for word enthusiasts.",
    link: "/apps/crossword",
    icon: "✍",
    tag: "Game",
    isComplete: false,
    categories: ["Entertainment", "Games"],
  },
  {
    title: "Currency Converter",
    description:
      "Enable seamless currency conversion with the Currency Converter, offering up-to-date exchange rates.",
    link: "/apps/currency-converter",
    icon: "💲",
    tag: "Latest",
    isComplete: false,
    categories: ["Finance", "Utility"],
  },
  {
    title: "PDF Converter",
    description:
      "Create PDFs instantly with the PDF Generator, simplifying document creation and sharing.",
    link: "/apps/pdf-converter",
    icon: "📄",
    tag: "Latest",
    isComplete: false,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "Microsoft Word Converter",
    description: "Convert Microsoft Words into another formats.",
    link: "/apps/word-converter",
    icon: "📝",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "Ping Pong",
    description:
      "Compete in a fast-paced game of Ping Pong, perfect for some quick entertainment.",
    link: "/apps/ping-pong",
    icon: "🏓",
    tag: "Game",
    isComplete: false,
    categories: ["Entertainment", "Games"],
  },
  {
    title: "PowerPoint Converter",
    description: "Convert PowerPoint presentations to different formats.",
    link: "/apps/powerpoint-converter",
    icon: "🖥",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "MP4 Converter",
    description: "Convert MP4 files to other video formats.",
    link: "/apps/mp4-converter",
    icon: "🎥",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Media"],
  },
  {
    title: "MP3 Converter",
    description: "Convert MP3 files to other audio formats.",
    link: "/apps/mp3-converter",
    icon: "🎵",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Media"],
  },
  {
    title: "Hangman",
    description:
      "Guess the word and test your vocabulary skills with the Hangman game, fun for players of all ages.",
    link: "/apps/hangman",
    icon: "🪝",
    tag: "Game",
    isComplete: false,
    categories: ["Entertainment", "Games"],
  },
  {
    title: "Horoscope",
    description: "Get insights into your future with daily horoscope readings.",
    link: "/apps/horoscope",
    icon: "🔮",
    tag: "General",
    isComplete: false,
    categories: ["General"],
  },
  {
    title: "Image Editor",
    description:
      "Refine visuals effortlessly using the Image Editor, ideal for enhancing photos and graphics.",
    link: "/apps/image-editor",
    icon: "🖼️",
    tag: "General",
    isComplete: false,
    categories: ["Media"],
  },
  {
    title: "Interest Calculator",
    description: "Calculate interest for loans, savings, and investments.",
    link: "/apps/interest-calculator",
    icon: "💰",
    tag: "General",
    isComplete: true,
    categories: ["Finance", "Utility"],
  },
  {
    title: "Jokes",
    description:
      "Experience daily doses of laughter with a delightful array of humor, providing the perfect mood boost for every occasion.",
    link: "/apps/jokes",
    icon: "🎭",
    tag: "General",
    isComplete: false,
    categories: ["Entertainment"],
  },
  {
    title: "JPG Converter",
    description: "Convert JPG image files to other formats.",
    link: "/apps/jpg-converter",
    icon: "🖼️",
    tag: "General",
    isComplete: false,
    categories: ["Media", "Utility"],
  },
  {
    title: "Webp Converter",
    description: "Convert webp image files to other formats.",
    link: "/apps/webp-converter",
    icon: "🖼️",
    tag: "General",
    isComplete: false,
    categories: ["Media", "Utility"],
  },
  {
    title: "Name Generator",
    description: "Generate random names for characters, products, and more.",
    link: "/apps/name-generator",
    icon: "📛",
    tag: "General",
    isComplete: false,
    categories: ["Utility"],
  },
  {
    title: "Password Generator",
    description: "Create secure passwords with the Password Generator tool.",
    link: "/apps/password-generator",
    icon: "🔐",
    tag: "General",
    isComplete: true,
    categories: ["Security", "Utility"],
  },
  {
    title: "PDF Generator",
    description: "Quickly generate PDF documents for various purposes.",
    link: "/apps/pdf-generator",
    icon: "📄",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "PNG Converter",
    description: "Convert PNG image files to other formats.",
    link: "/apps/png-converter",
    icon: "🖼️",
    tag: "General",
    isComplete: false,
    categories: ["Utility", "Media"],
  },
  {
    title: "QR Generator",
    description:
      "Generate QR codes instantly with the QR Generator, simplifying data sharing and communication.",
    link: "/apps/qr-generator",
    icon: "🏁",
    tag: "Latest",
    isComplete: true,
    categories: ["Utility"],
  },
  {
    title: "Quiz Game",
    description:
      "Test your knowledge with the Quiz App, featuring fun and challenging questions on various topics.",
    link: "/apps/quiz-game",
    icon: "🤔",
    tag: "Game",
    isComplete: false,
    categories: ["Entertainment", "Games"],
  },
  {
    title: "Quotes",
    icon: "💭",
    description:
      "Discover inspiration through an incredible selection of thought-provoking quotes to inspire, and motivate you.",
    link: "/apps/quotes",
    tag: "General",
    isComplete: false,
    categories: ["General"],
  },
  {
    title: "Sitemap Compiler",
    description:
      "Simplify website organization with the Sitemap Compiler, making `sitemap.xml` generation effortless.",
    link: "/apps/sitemap-compiler",
    icon: "🗊",
    tag: "Latest",
    isComplete: true,
    categories: ["Utility"],
  },
  {
    title: "Snake",
    description:
      "Navigate the snake and gobble up food to grow longer in the Snake game, a timeless classic for all ages.",
    link: "/apps/snake",
    icon: "🐍",
    tag: "Game",
    isComplete: false,
    categories: ["Entertainment", "Games"],
  },
  {
    title: "Sort Lists",
    description:
      "Quickly sort lists with the Sort Lists tool, facilitating better organization and management.",
    link: "/apps/sort-lists",
    icon: "🔀",
    tag: "General",
    isComplete: true,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "Summary Generator",
    description:
      "Save time by reading summaries generated by the Summary Generator instead of reading lengthy articles.",
    link: "/apps/summary-generator",
    icon: "🗒",
    tag: "Latest",
    isComplete: false,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "Tic-Tac-Toe",
    description:
      "Enjoy classic fun and challenge your friends with the Tic-Tac-Toe game, perfect for passing the time.",
    link: "/apps/tic-tac-toe",
    icon: "❌",
    tag: "Game",
    isComplete: true,
    categories: ["Entertainment", "Games"],
  },
  {
    title: "Timer",
    description:
      "Enhance productivity and time management with timer, ensuring focused task completion.",
    link: "/apps/timer",
    icon: "⏱️",
    tag: "General",
    isComplete: true,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "To-Do",
    description:
      "Stay organized and on top of your tasks with the To-Do App for management of your daily agenda and deadlines.",
    link: "/apps/to-do",
    icon: "🎯",
    tag: "Latest",
    isComplete: true,
    categories: ["Productivity", "Utility"],
  },
  {
    title: "Translator",
    description:
      "Translate your text into over 100 plus languages using the translator tool.",
    link: "/apps/translator",
    icon: "🔣",
    tag: "General",
    isComplete: true,
    categories: ["Utility"],
  },
  {
    title: "Trivia",
    description:
      "Test your knowledge and have fun with the Trivia game, offering questions on a variety of topics.",
    link: "/apps/trivia",
    icon: "🧩",
    tag: "Game",
    isComplete: false,
    categories: ["Entertainment", "Games"],
  },
  {
    title: "Video Downloader",
    description:
      "Effortlessly download videos with the Video Downloader, enabling offline viewing of your favorite content.",
    link: "/apps/video-downloader",
    icon: "▶️",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Media"],
  },
  {
    title: "Video Editor",
    description:
      "Elevate your videos with the Video Editor, offering powerful editing tools for professional-quality content.",
    link: "/apps/video-editor",
    icon: "🎞️",
    tag: "General",
    isComplete: false,
    categories: ["Productivity", "Media"],
  },
  {
    title: "Word Scramble",
    description:
      "Challenge your vocabulary and unscramble words to test your skills with the Word Scramble game.",
    link: "/apps/word-scramble",
    icon: "🔠",
    tag: "Game",
    isComplete: false,
    categories: ["Entertainment", "Games"],
  },
  {
    title: "World Clock",
    description:
      "Keep track of time around the globe with the World Clock, providing real-time updates for various time zones.",
    link: "/apps/world-clock",
    icon: "🕓",
    tag: "Latest",
    isComplete: false,
    categories: ["Productivity", "Utility"],
  },
];

export default LIST_OF_APPS;
