export const LIST_OF_APPS = [
  {
    title: "AI Prompts",
    description:
      "Unlock your creativity with AI Prompts, generating endless inspiration for your next project or idea.",
    link: "",
    icon: "🤖",
    tag: "general",
    category: ["Tools"],
  },
  {
    title: "Audio Downloader",
    description:
      "Effortlessly download audio with the Audio Downloader, for offline enjoyment of your favorite music and podcasts.",
    link: "",
    icon: "🎵",
    tag: "general",
    category: ["Tools"],
  },
  {
    title: "Book Summary",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "Color Generator",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "Cookie Details",
    description:
      "Gain insight into website cookies with Cookie Details, offering transparency and browsing control.",
    link: "",
    icon: "🍪",
    tag: "latest",
    category: ["Tools"],
  },
  {
    title: "Countdown",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "Crossword",
    description:
      "Challenge yourself with the interactive Crossword puzzle, perfect for word enthusiasts.",
    link: "",
    icon: "✍",
    tag: "game",
    category: ["Tools"],
  },
  {
    title: "Currency Converter",
    description:
      "Enable seamless currency conversion with the Currency Converter, offering up-to-date exchange rates.",
    link: "",
    icon: "💲",
    tag: "latest",
    category: ["Tools"],
  },
  {
    title: "PDF Converter",
    description:
      "Create PDFs instantly with the PDF Generator, simplifying document creation and sharing.",
    link: "",
    icon: "📄",
    tag: "latest",
    category: ["Tools"],
  },
  {
    title: "Word Converter",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "Ping Pong",
    description:
      "Compete in a fast-paced game of Ping Pong, perfect for some quick entertainment.",
    link: "",
    icon: "⚾",
    tag: "game",
    category: ["Tools"],
  },
  {
    title: "PowerPoint Converter",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "MP4 Converter",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "MP3 Converter",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "Hangman",
    description:
      "Guess the word and test your vocabulary skills with the Hangman game, fun for players of all ages.",
    link: "",
    icon: "🪝",
    tag: "game",
    category: ["Tools"],
  },
  {
    title: "Horoscope",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "Image Editor",
    description:
      "Refine visuals effortlessly using the Image Editor, ideal for enhancing photos and graphics.",
    link: "",
    icon: "🖼️",
    tag: "general",
    category: ["Tools"],
  },
  {
    title: "Interest Rate Calculator",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "Jokes",
    description:
      "Experience daily doses of laughter with a delightful array of humor, providing the perfect mood boost for every occasion.",
    link: "",
    icon: "🎭",
    tag: "general",
    category: ["Tools"],
  },
  {
    title: "JPG Converter",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "JPEG Converter",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "Name Generator",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "Password Generator",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "PDF Generator",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "PDF Coverter",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "PNG Converter",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "QR Generator",
    description:
      "Generate QR codes instantly with the QR Generator, simplifying data sharing and communication.",
    link: "",
    icon: "🏁",
    tag: "latest",
    category: ["Tools"],
  },
  {
    title: "Quiz Game",
    description:
      "Test your knowledge with the Quiz App, featuring fun and challenging questions on various topics.",
    link: "",
    icon: "🤔",
    tag: "game",
    category: ["Tools"],
  },
  {
    title: "Quotes",
    icon: "💭",
    description:
      "Discover inspiration through an incredible selection of thought-provoking quotes to inspire, and motivate you.",
    link: "",
    tag: "general",
    category: ["Tools"],
  },
  {
    title: "Recipe Finder",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "Sitemap Compiler",
    description:
      "Simplify website organization with the Sitemap Compiler, making `sitemap.xml` generation effortless.",
    link: "",
    icon: "🗊",
    tag: "latest",
    category: ["Tools"],
  },
  {
    title: "Snake",
    description:
      "Navigate the snake and gobble up food to grow longer in the Snake game, a timeless classic for all ages.",
    link: "",
    icon: "🐍",
    tag: "game",
    category: ["Tools"],
  },
  {
    title: "Sort Lists",
    description: "",
    link: "",
    icon: "",
    tag: "",
    category: ["Tools"],
  },
  {
    title: "Summary Generator",
    description:
      "Save time by reading summaries generated by the Summary Generator instead of reading lengthy articles.",
    link: "",
    icon: "🗒",
    tag: "latest",
    category: ["Tools"],
  },
  {
    title: "Tic-Tac-Toe",
    description:
      "Enjoy classic fun and challenge your friends with the Tic-Tac-Toe game, perfect for passing the time.",
    link: "",
    icon: "❌",
    tag: "game",
    category: ["Tools"],
  },
  {
    title: "Timer",
    description:
      "Enhance productivity and time management with timer, ensuring focused task completion.",
    link: "",
    icon: "⏱️",
    tag: "general",
    category: ["Tools"],
  },
  {
    title: "To-Do",
    description:
      "Stay organized and on top of your tasks with the To-Do App for management of your daily agenda and deadlines.",
    link: "",
    icon: "🎯",
    tag: "latest",
    category: ["Tools"],
  },
  {
    title: "Trivia Game",
    description:
      "Test your knowledge and have fun with the Trivia game, offering questions on a variety of topics.",
    link: "",
    icon: "🧩",
    tag: "game",
    category: ["Tools"],
  },
  {
    title: "Video Downloader",
    description:
      "Effortlessly download videos with the Video Downloader, enabling offline viewing of your favorite content.",
    link: "",
    icon: "▶️",
    tag: "general",
    category: ["Tools"],
  },
  {
    title: "Video Editor",
    description:
      "Elevate your videos with the Video Editor, offering powerful editing tools for professional-quality content.",
    link: "",
    icon: "🎞️",
    tag: "general",
    category: ["Tools"],
  },
  {
    title: "Word Scramble",
    description:
      "Challenge your vocabulary and unscramble words to test your skills with the Word Scramble game.",
    link: "",
    icon: "🔠",
    tag: "game",
    category: ["Tools"],
  },
  {
    title: "World Clock",
    description:
      "Keep track of time around the globe with the World Clock, providing real-time updates for various time zones.",
    link: "",
    icon: "🕓",
    tag: "latest",
    category: ["Tools"],
  },
];
